name: bsc-gcp-foundation-layer
on: 
  workflow_dispatch:
    inputs:
      version:
        description: GCP Foundation layer
        default: v1.0.0
        required: true
env:
  TAG: 1.0.0

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform -chdir=dev init
     
    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform -chdir=dev  fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform -chdir=dev  plan
      
 #   - name: Terraform Apply
 #     if: github.ref == 'refs/heads/main' && github.event_name == 'push'
 #     run: terraform -chdir=dev  apply -auto-approve
